name: Label PR based on file names

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  apply-labels:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get list of changed files
      id: changed_files
      run: |
        git fetch --depth=1
        FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
        echo "FILES=$FILES" >> $GITHUB_ENV  # Armazena os arquivos em um arquivo de ambiente
        echo "Changed files: $FILES"  # Imprime os arquivos modificados no log

    - name: Apply labels
      if: steps.changed_files.outputs.files != ''
      run: |
        echo "FILES from previous step: ${{ steps.changed_files.outputs.files }}"
        # Resto do código...

    - name: Set GitHub labels
      uses: actions/github-script@v6
      with:
        script: |
          const labels = process.env.LABELS.split(',');
          const prNumber = context.issue.number;

          if (labels.length > 0 && labels[0] !== "") {
            // Aplica as labels ao PR
            await github.rest.issues.addLabels({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: labels,
            });
            console.log(`Labels applied: ${labels}`);
          } else {
            console.log("No labels to apply.");
          }
